# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# New window with 'prefix c'
bind c new-window

# Kill session with 'prefix k'
bind k kill-session

# Kill server with 'prefix K'
bind K kill-server

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind-key -r < swap-window -d -t -1
bind-key -r > swap-window -d -t +1

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# don't rename windows automatically
set-option -g allow-rename off

# True color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=blue'

set -g status-left ' #{session_name}  '
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '#[fg=black bg=yellow]%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=blue'
setw -g window-status-current-format '#[fg=black bg=blue] #I #W #F'

setw -g window-status-style 'fg=blue bg=black'
setw -g window-status-format '#[fg=blue] #I #[fg=white]#W#[fg=yellow] #F'
# setw -g window-status-format '#[fg=#23273a bg=black]#[fg=blue] #I #[fg=white]#W #[fg=yellow]#F#[fg=black bg=#23273a]'


setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
set -g message-style 'fg=yellow bg=blue bold'

